version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ourgym_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ourgym
      MYSQL_USER: ourgym
      MYSQL_PASSWORD: ourgym
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    container_name: ourgym_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://ourgym:ourgym@db:3306/ourgym"
    command: php -S 0.0.0.0:8000 -t public

volumes:
  db_data:
